services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: inmobiliaria-app
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    env_file:
      - .env

