version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inmobiliaria-app
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    env_file:
      - .env
    environment:
      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      - migrate
    deploy:
      resources:
        limits:
          memory: 2GB

  migrate:
    image: node:20
    container_name: prisma-migrate
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: ["sh", "-c", "corepack enable && pnpm install --frozen-lockfile && npx prisma generate && npx prisma migrate deploy"]
