name: Deploy to EC2

on:
  push:
    branches:
      - develop 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH and Deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Ensure repository exists, else clone
          if [ ! -d "~/inmobiliaria-back/.git" ]; then
            rm -rf ~/inmobiliaria-back
            git clone https://github.com/jcsoftdev/inmobiliaria-back.git ~/inmobiliaria-back
          fi

          # Navigate to project, pull latest code from develop
          cd ~/inmobiliaria-back
          git checkout develop
          git pull origin develop

          # Stop, remove old containers, and start new ones
          docker compose down
          docker compose up -d --build
        EOF
