name: Deploy to EC2

on:
  push:
    branches:
      - develop 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH and Deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Backup the .env file if it exists
            if [ -f ~/inmobiliaria-back/.env ]; then
              mv ~/inmobiliaria-back/.env ~/.env_backup
            fi

            sudo rm -rf ~/inmobiliaria-back
            git clone https://github.com/jcsoftdev/inmobiliaria-back.git ~/inmobiliaria-back

            if [ -f ~/.env_backup ]; then
              mv ~/.env_backup ~/inmobiliaria-back/.env
            fi

            cd ~/inmobiliaria-back
            git checkout develop
            git pull origin develop

            docker-compose up -d --no-deps --build

            docker image prune -f
            docker container prune -f
          EOF
